### ISSUE TITLE
Contributors/Backend guideline page missing

### ISSUE THREAD

**Issue by ghost** [DenizenScript/Denizen-For-Bukkit-Docs#12]
I had completely forgot that this should be a thing. Thanks to @SXRWahrheit for pointing this out to me on Discord!

**Comment by mcmonkey4eva** [comment]
This does exist now: https://github.com/DenizenScript/Denizen-For-Bukkit-Docs/blob/master/CONTRIB_GUIDELINES.md
Is there anything more to the issue?

**Comment by ghost** [comment]
There has been no issue raised about it being vague so far, so I think I'll close this issue.
